version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - DB_URI=mongodb://mongo:27017/faqs
      - REDIS_HOST=redis
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
