version: '3.8'

services:
  app:
    build: .
    container_name: faq-api-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/faq-api
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:latest
    container_name: faq-api-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
